Cleaning up git plugin.

diff --git a/zsh/plugins/git/functions/gitid b/zsh/plugins/git/functions/gitid
--- a/zsh/plugins/git/functions/gitid
+++ b/zsh/plugins/git/functions/gitid
@@ -2,18 +2,18 @@
 
 local bn=$(basename ${0})
 
-function __hszsh-git-identity-error()
+function __hszsh_gitid-error()
 {
   echo "${bn}: error: ${*}" >&2
 }
 
-function __hszsh-git-identity-usage()
+function __hszsh_gitid-usage()
 {
   cat >&2 <<EOS
 
 Usage: ${bn} add|set IDENTITY-NAME "NAME" "email"
        ${bn} remove IDENTITY-NAME
-       ${bn} use IDENTITY-NAME
+       ${bn} [use] IDENTITY-NAME
        ${bn} show IDENTITY-NAME
        ${bn} list IDENTITY-NAME
 
@@ -21,43 +21,43 @@ Manages or uses git user identities.
 EOS
 }
 
-function __hszsh-git-identity-exists()
+function __hszsh_gitid-exists()
 {
-  if [ ! -f ${__hszsh_git_plugin_identity_path}/${1} ]; then
-    __hszsh-git-identity-error "git-identity \"${1}\" does not exist."
+  if [ ! -f "${__hszsh_git_plugin_identity_path}/${1}" ]; then
+    __hszsh_gitid-error "gitid \"${1}\" does not exist."
     return 127
   fi
 
   return 0
 }
 
-function __hszsh-git-identity-remove()
+function __hszsh_gitid-remove()
 {
-  __hszsh-git-identity-exists ${1} || return
+  __hszsh_gitid-exists ${1} || return
 
-  echo "Removing git-identity \"${1}\"."
-  rm -f ${__hszsh_git_plugin_identity_path}/${1}
+  echo "Removing gitid \"${1}\"."
+  rm -f "${__hszsh_git_plugin_identity_path}/${1}"
 }
 
-function __hszsh-git-identity-use()
+function __hszsh_gitid-use()
 {
-  __hszsh-git-identity-exists ${1} || return
+  __hszsh_gitid-exists ${1} || return
 
-  echo "Using git-identity \"${1}\"."
-  source ${__hszsh_git_plugin_identity_path}/${1}
+  echo "Using gitid \"${1}\"."
+  source "${__hszsh_git_plugin_identity_path}/${1}"
 }
 
-function __hszsh-git-identity-show()
+function __hszsh_gitid-show()
 {
-  __hszsh-git-identity-exists ${1} || return
+  __hszsh_gitid-exists ${1} || return
 
-  echo "git-identity \"${1}\":"
-  cat ${__hszsh_git_plugin_identity_path}/${1}
+  echo "gitid \"${1}\":"
+  cat "${__hszsh_git_plugin_identity_path}/${1}"
 }
 
-function __hszsh-git-identity-add()
+function __hszsh_gitid-add()
 {
-  cat > ${__hszsh_git_plugin_identity_path}/${1} <<EOS
+  cat > "${__hszsh_git_plugin_identity_path}/${1}" <<EOS
 export GIT_AUTHOR_NAME="${2}"
 export GIT_AUTHOR_EMAIL="${3}"
 
@@ -66,7 +66,7 @@ export GIT_COMMITTER_EMAIL="${3}"
 EOS
 }
 
-function __hszsh-git-identity-list()
+function __hszsh_gitid-list()
 {
   if [ ${#identities} -eq 0 ]; then
     echo "No identities defined."
@@ -82,14 +82,14 @@ function __hszsh-git-identity-list()
 }
 
 if [ -z "${__hszsh_git_plugin_identity_path}" ]; then
-  __hszsh-git-identity-error "Missing the identity path."
-  __hszsh-git-identity-usage
+  __hszsh_gitid-error "Missing the identity path."
+  __hszsh_gitid-usage
   return 1
 fi
 
 if [ ${#} -eq 0 ]; then
-  __hszsh-git-identity-error "No command given."
-  __hszsh-git-identity-usage
+  __hszsh_gitid-error "No command given."
+  __hszsh_gitid-usage
   return 1
 fi
 
@@ -97,33 +97,41 @@ local command_name="${1}"
 shift 1
 
 local -a identities
-identities=(${__hszsh_git_plugin_identity_path}/*(.N))
+identities=("${__hszsh_git_plugin_identity_path}"/*(.N))
 
 local command_match=$(echo "${command_name}" | tr A-Z a-z)
 local -i required_params=0
 
 case "${command_match}" in
-  add|set)      # git-identity add|set IDENTITY-NAME "NAME" "email"
+  add|set)
+    # gitid add|set IDENTITY-NAME "NAME" "email"
     required_params=3
     command_match=add
     ;;
-  remove|show|use)   # git-identity remove|show|use IDENTITY-NAME
+  remove|show|use)
+    # gitid remove|show|use IDENTITY-NAME
     required_params=1
     ;;
-  list)     # git-identity list
+  list)
+    # gitid list
     required_params=0
     ;;
   *)
-    __hszsh-git-identity-error "Unknown command \"${command_name}\"."
-    __hszsh-git-identity-usage
+    if __hszsh_gitid-exists ${command_name}; then
+      __hszsh_gitid-use ${command_name}
+      return 0
+    fi
+
+    __hszsh_gitid-error "Unknown command \"${command_name}\"."
+    __hszsh_gitid-usage
     return 2
     ;;
 esac
 
 if [ "${#}" -ne ${required_params} ]; then
-  __hszsh-git-identity-error "Invalid parameter count for \"${command_name}\"."
-  __hszsh-git-identity-usage
+  __hszsh_gitid-error "Invalid parameter count for \"${command_name}\"."
+  __hszsh_gitid-usage
   return 3
 fi
 
-__hszsh-git-identity-${command_match} "${@}"
+__hszsh_gitid-${command_match} "${@}"
