Omnibus commit because I'm lazy.
- Updating my gitconfig to make a few things cleaner and do something a
  little smarter with aliases.
- Added a package generator for Hg and Git packages.
- Adding a few packages related to Pivotal Tracker.
- Removing unnecessary vim: flag comments on zsh function files.
- Renamed a few functions.
- Made a few functions more zsh-ish.

diff --git a/zsh/plugins/git/functions/gitid b/zsh/plugins/git/functions/gitid
--- a/zsh/plugins/git/functions/gitid
+++ b/zsh/plugins/git/functions/gitid
@@ -2,12 +2,12 @@
 
 local bn=$(basename ${0})
 
-function __hzsh_gitid-error()
+function --hzsh-gitid-error()
 {
   echo "${bn}: error: ${*}" >&2
 }
 
-function __hzsh_gitid-usage()
+function --hzsh-gitid-usage()
 {
   cat >&2 <<EOS
 
@@ -31,48 +31,48 @@ Manages or uses git user identities.
 EOS
 }
 
-function __hzsh_gitid-exists()
+function --hzsh-gitid-exists()
 {
-  if [ ! -f "${__hzsh_git_plugin_identity_path}/${1}" ]; then
-    __hzsh_gitid-error "gitid \"${1}\" does not exist."
+  if [ ! -f "${__hzsh_plugins_git_identity_path}/${1}" ]; then
+    --hzsh-gitid-error "gitid \"${1}\" does not exist."
     return 127
   fi
 
   return 0
 }
 
-function __hzsh_gitid-remove()
+function --hzsh-gitid-remove()
 {
-  __hzsh_gitid-exists ${1} || return
+  --hzsh-gitid-exists ${1} || return
 
   echo "Removing gitid \"${1}\"."
-  rm -f "${__hzsh_git_plugin_identity_path}/${1}"
+  rm -f "${__hzsh_plugins_git_identity_path}/${1}"
 }
 
-function __hzsh_gitid-use()
+function --hzsh-gitid-use()
 {
-  __hzsh_gitid-exists ${1} || return
+  --hzsh-gitid-exists ${1} || return
 
   echo "Using gitid \"${1}\"."
-  source "${__hzsh_git_plugin_identity_path}/${1}"
+  source "${__hzsh_plugins_git_identity_path}/${1}"
 }
 
-function __hzsh_gitid-clear()
+function --hzsh-gitid-clear()
 {
-  unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITER_NAME GIT_COMMITER_EMAIL
+  unset GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
 }
 
-function __hzsh_gitid-show()
+function --hzsh-gitid-show()
 {
-  __hzsh_gitid-exists ${1} || return
+  --hzsh-gitid-exists ${1} || return
 
   echo "gitid \"${1}\":"
-  cat "${__hzsh_git_plugin_identity_path}/${1}"
+  cat "${__hzsh_plugins_git_identity_path}/${1}"
 }
 
-function __hzsh_gitid-add()
+function --hzsh-gitid-add()
 {
-  cat > "${__hzsh_git_plugin_identity_path}/${1}" <<EOS
+  cat > "${__hzsh_plugins_git_identity_path}/${1}" <<EOS
 export GIT_AUTHOR_NAME="${2}"
 export GIT_AUTHOR_EMAIL="${3}"
 
@@ -81,7 +81,7 @@ export GIT_COMMITTER_EMAIL="${3}"
 EOS
 }
 
-function __hzsh_gitid-list()
+function --hzsh-gitid-list()
 {
   if [ ${#identities} -eq 0 ]; then
     echo "No identities defined."
@@ -96,26 +96,26 @@ function __hzsh_gitid-list()
   fi
 }
 
-if [ -z "${__hzsh_git_plugin_identity_path}" ]; then
-  __hzsh_gitid-error "Missing the identity path."
-  __hzsh_gitid-usage
+if [ -z "${__hzsh_plugins_git_identity_path}" ]; then
+  --hzsh-gitid-error "Missing the identity path."
+  --hzsh-gitid-usage
   return 1
 fi
 
 if [ ${#} -eq 0 ]; then
-  __hzsh_gitid-error "No command given."
-  __hzsh_gitid-usage
+  --hzsh-gitid-error "No command given."
+  --hzsh-gitid-usage
   return 1
 fi
 
-[ -d "${__hzsh_git_plugin_identity_path}" ] ||
-  mkdir -p "${__hzsh_git_plugin_identity_path}"
+[ -d "${__hzsh_plugins_git_identity_path}" ] ||
+  mkdir -p "${__hzsh_plugins_git_identity_path}"
 
 local command_name="${1}"
 shift 1
 
 local -a identities
-identities=("${__hzsh_git_plugin_identity_path}"/*(.N))
+identities=("${__hzsh_plugins_git_identity_path}"/*(.N))
 
 local command_match=$(echo "${command_name}" | tr A-Z a-z)
 local -i required_params=0
@@ -130,26 +130,26 @@ case "${command_match}" in
     # gitid remove|show|use IDENTITY-NAME
     required_params=1
     ;;
-  list)
+  list|clear)
     # gitid list
     required_params=0
     ;;
   *)
-    if __hzsh_gitid-exists ${command_name}; then
-      __hzsh_gitid-use ${command_name}
+    if --hzsh-gitid-exists ${command_name}; then
+      --hzsh-gitid-use ${command_name}
       return 0
     fi
 
-    __hzsh_gitid-error "Unknown command \"${command_name}\"."
-    __hzsh_gitid-usage
+    --hzsh-gitid-error "Unknown command \"${command_name}\"."
+    --hzsh-gitid-usage
     return 2
     ;;
 esac
 
 if [ "${#}" -ne ${required_params} ]; then
-  __hzsh_gitid-error "Invalid parameter count for \"${command_name}\"."
-  __hzsh_gitid-usage
+  --hzsh-gitid-error "Invalid parameter count for \"${command_name}\"."
+  --hzsh-gitid-usage
   return 3
 fi
 
-__hzsh_gitid-${command_match} "${@}"
+--hzsh-gitid-${command_match} "${@}"
